name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: yarn test
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: ArtiomTr/jest-coverage-report-action@v2
