name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn
    - uses: actions/upload-artifact@master
      with:
        name: artifact
        path: /
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@master
      with:
        name: artiface
        path: /
    - name: Run tests
      run: yarn && yarn test
  coverage:
    permissions:
      checks: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v1
        - uses: ArtiomTr/jest-coverage-report-action@v2
